init -1 python:
    # prevent choosing name already used in game
    def get_unused_name():
        names = [person.name for person in all_people_in_the_game()]
        return get_random_from_list(list(set(list_of_names)-set(names)))

    get_random_name = get_unused_name

    # prevent choosing last_name already used in game
    def get_unused_last_name():
        names = [person.last_name for person in all_people_in_the_game()]
        return get_random_from_list(list(set(list_of_last_names)-set(names)))

    get_random_last_name = get_unused_last_name

    # Remove default names for unique characters from possible name list
    if "Candace" in list_of_names:
        list_of_names.remove("Candace")
    if "Ashley" in list_of_names:
        list_of_names.remove("Ashley")
    if "Emily" in list_of_names:
        list_of_names.remove("Emily")
    if "Christina" in list_of_names:
        list_of_names.remove("Christina")
    if "Christine" in list_of_names:
        list_of_names.remove("Christine")
    if "Gabrielle" in list_of_names:
        list_of_names.remove("Gabrielle")
    if "Rebecca" in list_of_names:
        list_of_names.remove("Rebecca")
    if "Stephanie" in list_of_names:
        list_of_names.remove("Stephanie")
    if "Cara" in list_of_names:
        list_of_names.remove("Cara")
    if "Erica" in list_of_names:
        list_of_names.remove("Erica")
    if "Kaya" in list_of_names:
        list_of_names.remove("Kaya")
    if "Sakari" in list_of_names:
        list_of_names.remove("Sakari")
    if "Ellie" in list_of_names:
        list_of_names.remove("Ellie")
    if "Sarah" in list_of_names:
        list_of_names.remove("Sarah")
    if "Ophelia" in list_of_names:
        list_of_names.remove("Ophelia")

    if "Rojas" in list_of_last_names:
        list_of_last_names.remove("Rojas")
    if "Hooper" in list_of_last_names:
        list_of_last_names.remove("Hooper")
    if "Lavardin" in list_of_last_names:
        list_of_last_names.remove("Lavardin")
    if "Greene" in list_of_last_names:
        list_of_last_names.remove("Greene")
    if "von Friseur" in list_of_last_names:
        list_of_last_names.remove("von Friseur")
    if "Coopers" in list_of_last_names:
        list_of_last_names.remove("Coopers")
    if "Walters" in list_of_last_names:
        list_of_last_names.remove("Walters")

    # Extra names provided by LangyMD (based on US consensus)
    list_of_names.append("Mary")
    list_of_names.append("Patricia")
    list_of_names.append("Linda")
    list_of_names.append("Barbara")
    list_of_names.append("Margaret")
    list_of_names.append("Dorothy")
    list_of_names.append("Lisa")
    list_of_names.append("Nancy")
    list_of_names.append("Karen")
    list_of_names.append("Betty")
    list_of_names.append("Donna")
    list_of_names.append("Carol")
    list_of_names.append("Ruth")
    list_of_names.append("Sharon")
    list_of_names.append("Michelle")
    list_of_names.append("Laura")
    list_of_names.append("Kimberly")
    list_of_names.append("Deborah")
    list_of_names.append("Cynthia")
    list_of_names.append("Melissa")
    list_of_names.append("Brenda")
    list_of_names.append("Amy")
    list_of_names.append("Virginia")
    list_of_names.append("Kathleen")
    list_of_names.append("Pamela")
    list_of_names.append("Martha")
    list_of_names.append("Debra")
    list_of_names.append("Amanda")
    list_of_names.append("Carolyn")
    # Popular Names from UK census
    list_of_names.append("Amelia")
    list_of_names.append("Ava")
    list_of_names.append("Mia")
    list_of_names.append("Grace")
    list_of_names.append("Sophia")
    list_of_names.append("Aisha")
    list_of_names.append("Ivy")
    list_of_names.append("Ella")
    list_of_names.append("Florence")
    list_of_names.append("Willow")
    list_of_names.append("Phoebe")
    list_of_names.append("Sienna")
    list_of_names.append("Ruby")
    list_of_names.append("Harper")
    list_of_names.append("Luna")
    list_of_names.append("Eliza")
    list_of_names.append("Chloe")
    list_of_names.append("Maisie")

    # Extra last names provided by LangyMD (based on US consensus)
    list_of_last_names.append("Smith")
    list_of_last_names.append("Johnson")
    list_of_last_names.append("Brown")
    list_of_last_names.append("Davis")
    list_of_last_names.append("Miller")
    list_of_last_names.append("Wilson")
    list_of_last_names.append("Moore")
    list_of_last_names.append("Taylor")
    list_of_last_names.append("Thomas")
    list_of_last_names.append("Jackson")
    list_of_last_names.append("White")
    list_of_last_names.append("Harris")
    list_of_last_names.append("Martin")
    list_of_last_names.append("Thompson")
    list_of_last_names.append("Garcia")
    list_of_last_names.append("Robinson")
    list_of_last_names.append("Clark")
    list_of_last_names.append("Lewis")
    list_of_last_names.append("Walker")
    list_of_last_names.append("Hall")
    list_of_last_names.append("Allen")
    list_of_last_names.append("Young")
    list_of_last_names.append("King")
    list_of_last_names.append("Wright")
    list_of_last_names.append("Hill")
    list_of_last_names.append("Scott")
    list_of_last_names.append("Green")
    list_of_last_names.append("Adams")

    # Extra male names provided by LangyMD (based on US consensus)
    list_of_male_names.append("James")
    list_of_male_names.append("John")
    list_of_male_names.append("Robert")
    list_of_male_names.append("Michael")
    list_of_male_names.append("David")
    list_of_male_names.append("Richard")
    list_of_male_names.append("Charles")
    list_of_male_names.append("Joseph")
    list_of_male_names.append("Christopher")
    list_of_male_names.append("Daniel")
    list_of_male_names.append("Paul")
    list_of_male_names.append("Mark")
    list_of_male_names.append("Donald")
    list_of_male_names.append("George")
    list_of_male_names.append("Kenneth")
    list_of_male_names.append("Steven")
    list_of_male_names.append("Edward")
    list_of_male_names.append("Brian")
    list_of_male_names.append("Ronald")
    list_of_male_names.append("Anthony")
    list_of_male_names.append("Kevin")
    list_of_male_names.append("Jason")
    list_of_male_names.append("Matthew")
    list_of_male_names.append("Gary")
    list_of_male_names.append("Timothy")
    list_of_male_names.append("Jose")
    list_of_male_names.append("Larry")
    list_of_male_names.append("Jeffrey")
    list_of_male_names.append("Frank")
    list_of_male_names.append("Eric")

    # Spanish
    list_of_names.append("Anahi")
    list_of_names.append("Belen")
    list_of_names.append("Dulce")
    list_of_names.append("Esperanza")
    list_of_names.append("Graciela")
    list_of_names.append("Izzabella")
    list_of_names.append("Mireya")
    list_of_names.append("Perla")
    list_of_names.append("Reina")
    list_of_names.append("Savanna")
    list_of_names.append("Yesenia")

    list_of_last_names.append("Alonso")
    list_of_last_names.append("Diaz")
    list_of_last_names.append("Gutierrez")
    list_of_last_names.append("Hernandez")
    list_of_last_names.append("Jimenez")
    list_of_last_names.append("Lopez")
    list_of_last_names.append("Martinez")
    list_of_last_names.append("Navarro")
    list_of_last_names.append("Rodriguez")
    list_of_last_names.append("Sanchez")


    # French
    list_of_names.append("Antoinette")
    list_of_names.append("Claudette")
    list_of_names.append("Dominique")
    list_of_names.append("Fleur")
    list_of_names.append("Josephine")
    list_of_names.append("Noelle")
    list_of_names.append("Solange")
    list_of_names.append("Veronique")
    list_of_names.append("Yvette")
    list_of_names.append("Zara")

    list_of_last_names.append("Baptiste")
    list_of_last_names.append("Belcourt")
    list_of_last_names.append("Dubois")
    list_of_last_names.append("Leclercq")
    list_of_last_names.append("Lefebvre")
    list_of_last_names.append("Moreau")
    list_of_last_names.append("Perrin")
    list_of_last_names.append("Rousseau")
    list_of_last_names.append("Vallet")
    list_of_last_names.append("Vivier")

    # German
    list_of_names.append("Anna")
    list_of_names.append("Charlotte")
    list_of_names.append("Emilie")
    list_of_names.append("Hannah")
    list_of_names.append("Ingrid")
    list_of_names.append("Klara")
    list_of_names.append("Lena")
    list_of_names.append("Mila")
    list_of_names.append("Ramona")
    list_of_names.append("Sabine")
    list_of_names.append("Sophie")

    list_of_last_names.append("Baumann")
    list_of_last_names.append("Fisher")
    list_of_last_names.append("Graf")
    list_of_last_names.append("Engel")
    list_of_last_names.append("Fisher")
    list_of_last_names.append("Krüger")
    list_of_last_names.append("Lehmann")
    list_of_last_names.append("Müller")
    list_of_last_names.append("Richter")
    list_of_last_names.append("Ziegler")

    # Italian
    list_of_names.append("Aurora")
    list_of_names.append("Celine")
    list_of_names.append("Chiara")
    list_of_names.append("Giulia")
    list_of_names.append("Eleonora")
    list_of_names.append("Francesca")
    list_of_names.append("Gaia")
    list_of_names.append("Ginevra")
    list_of_names.append("Ludovica")
    list_of_names.append("Martina")
    list_of_names.append("Noemi")

    list_of_last_names.append("Alfonsi")
    list_of_last_names.append("Bianchi")
    list_of_last_names.append("Cancio")
    list_of_last_names.append("Colombo")
    list_of_last_names.append("De Luca")
    list_of_last_names.append("Ferrari")
    list_of_last_names.append("Marino")
    list_of_last_names.append("Ricci")
    list_of_last_names.append("Russo")
    list_of_last_names.append("Greco")

    # African
    list_of_names.append("Ashanti")
    list_of_names.append("Eshe")
    list_of_names.append("Hadiyya")
    list_of_names.append("Kesia")
    list_of_names.append("Kalisha")
    list_of_names.append("Malaika")
    list_of_names.append("Poni")
    list_of_names.append("Radhiya")
    list_of_names.append("Shani")
    list_of_names.append("Zuri")

    list_of_last_names.append("Abebe")
    list_of_last_names.append("Alasa")
    list_of_last_names.append("Dogo")
    list_of_last_names.append("Jelani")
    list_of_last_names.append("Mensah")
    list_of_last_names.append("Ndiaye")
    list_of_last_names.append("Okoye")
    list_of_last_names.append("Osei")
    list_of_last_names.append("Temitope")
    list_of_last_names.append("Zivai")
