init -1 python:
    # Spanish
    list_of_names.append("Anahi")
    list_of_names.append("Belen")
    list_of_names.append("Dulce")
    list_of_names.append("Esperanza")
    list_of_names.append("Graciela")
    list_of_names.append("Izzabella")
    list_of_names.append("Mireya")
    list_of_names.append("Perla")
    list_of_names.append("Reina")
    list_of_names.append("Savanna")
    list_of_names.append("Yesenia")

    list_of_last_names.append("Alonso")
    list_of_last_names.append("Diaz")
    list_of_last_names.append("Gutierrez")
    list_of_last_names.append("Hernandez")
    list_of_last_names.append("Jimenez")
    list_of_last_names.append("Lopez")
    list_of_last_names.append("Martinez")
    list_of_last_names.append("Navarro")
    list_of_last_names.append("Rodriguez")
    list_of_last_names.append("Sanchez")


    # French
    list_of_names.append("Antoinette")
    list_of_names.append("Claudette")
    list_of_names.append("Dominique")
    list_of_names.append("Fleur")
    list_of_names.append("Josephine")
    list_of_names.append("Noelle")
    list_of_names.append("Solange")
    list_of_names.append("Veronique")
    list_of_names.append("Yvette")
    list_of_names.append("Zara")

    list_of_last_names.append("Baptiste")
    list_of_last_names.append("Belcourt")
    list_of_last_names.append("Dubois")
    list_of_last_names.append("Leclercq")
    list_of_last_names.append("Lefebvre")
    list_of_last_names.append("Moreau")
    list_of_last_names.append("Perrin")
    list_of_last_names.append("Rousseau")
    list_of_last_names.append("Vallet")
    list_of_last_names.append("Vivier")

    # German
    list_of_names.append("Anna")
    list_of_names.append("Charlotte")
    list_of_names.append("Emilie")
    list_of_names.append("Hannah")
    list_of_names.append("Ingrid")
    list_of_names.append("Klara")
    list_of_names.append("Lena")
    list_of_names.append("Mila")
    list_of_names.append("Ramona")
    list_of_names.append("Sabine")
    list_of_names.append("Sophie")

    list_of_last_names.append("Baumann")
    list_of_last_names.append("Fisher")
    list_of_last_names.append("Graf")
    list_of_last_names.append("Engel")
    list_of_last_names.append("Fisher")
    list_of_last_names.append("Krüger")
    list_of_last_names.append("Lehmann")
    list_of_last_names.append("Müller")
    list_of_last_names.append("Richter")
    list_of_last_names.append("Ziegler")
